#!/usr/bin/env bash

title=$(head -1 "$1")

if ! (echo "$title" | grep -qE "^Merge"); then
    if ! (echo "$title" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?!?: .{1,}$"); then
        echo "Aborting commit. Your commit message is invalid. Please follow the semantic commit guidelines" >&2
        exit 1
    fi
fi

if ! which aspell > /dev/null; then
    echo "Please install aspell for proper spell checking" >&2
    exit 1
fi

# Included because aliases aren't inherited by subshell
misspelled_words=$(cat "$1" | aspell --lang=en_US --personal="$HOME"/.aspell_en_dict --list | tr '\n' ' ')
if [ -n "$misspelled_words" ]; then
    echo "Found misspelled words: $misspelled_words" >&2
    echo "Would you like to add these to the dictionary? [y|n|s]" 
    read -r < /dev/tty
    if [ "$REPLY" = 'y' ] || [ "$REPLY" = 'Y' ]; then
        if ! which aspelladd > /dev/null; then
            echo "This operation requires the aspelladd binary, please add that. It can found at https://github.com/senyc/.dotfiles/tree/main/home/bin/aspelladd" >&2
            exit 1
        fi
        # **The lack of quotes is intentional**
        aspelladd $misspelled_words
        echo
    elif [ "$REPLY" = 's' ] || [ "$REPLY" = 'S' ]; then
        echo "Skipping..." 
    else 
        echo "Please fix the spelling mistakes and commit your changes again" 
        exit 1
    fi
fi
